server:
  port: 8400
  servlet:
    context-path: /sentinal-service
spring:
  application:
    name: sentinal-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: localhost:8848
        namespace: c31e593e-e3cc-493b-a0cd-f744c0f664b4 # 开发环境-nacos的命名空间I
    sentinel:
      transport:
        #配置Sentin dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'