server:
  port: 9012  #端口
spring:
  application:
    name: seata-account-service #服务名
  cloud:
    alibaba:
      seata:
        #自定义事务组名称 需要与seata-server中的对应
        tx-service-group: cl_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos 服务器地址
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
    url: jdbc:mysql://localhost:3306/seata_account
    username: root  #数据库的用户名
    password: 123456  #数据库密码
feign:
  hystrix:
    enabled: false
  ###################################### MyBatis 配置 ######################################
  #mybatis:
  #  # 指定 mapper.xml 的位置
  mapper-locations: classpath*:com/seata/account/dao/xml/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
#  type-aliases-package: com.seata.order.domain
#  configuration:
#    #默认开启驼峰命名法，可以不用设置该属性
#    map-underscore-to-camel-case: true